# Generated by Django 3.0.8 on 2020-07-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200731_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
