# Generated by Django 3.0.8 on 2020-08-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200731_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('0', 'Text'), ('1', 'Single'), ('2', 'Multiple')], default=0, max_length=1),
        ),
    ]
